# Generated by Django 5.0.2 on 2025-05-28 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomOAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=500)),
                ('refresh_token', models.CharField(max_length=500)),
                ('expires_in', models.IntegerField()),
                ('token_type', models.CharField(default='bearer', max_length=50)),
                ('scope', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zoom_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zoom OAuth Token',
                'verbose_name_plural': 'Zoom OAuth Tokens',
            },
        ),
    ]
