# Generated by Django 5.0.2 on 2025-05-29 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom_oauth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_type', models.CharField(choices=[('manual', 'Manually Created'), ('auto', 'Auto Created')], max_length=10)),
                ('meeting_id', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('host', models.CharField(max_length=255)),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='scheduled', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zoom_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zoom Meeting',
                'verbose_name_plural': 'Zoom Meetings',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='MeetingParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('join_time', models.DateTimeField()),
                ('leave_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='zoom_oauth.zoommeeting')),
            ],
            options={
                'verbose_name': 'Meeting Participant',
                'verbose_name_plural': 'Meeting Participants',
                'ordering': ['-join_time'],
            },
        ),
    ]
