# Generated by Django 5.0.2 on 2025-05-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom_oauth', '0002_zoommeeting_meetingparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoommeeting',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zoommeeting',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zoommeeting',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zoommeeting',
            name='last_status_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='zoommeeting',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('waiting', 'Waiting to Start'), ('in_progress', 'In Progress'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
    ]
