# Generated by Django 5.0.2 on 2025-05-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom_oauth', '0003_zoommeeting_duration_zoommeeting_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoommeeting',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
    ]
