# Generated by Django 5.0.2 on 2025-05-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_alter_meeting_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='zoom_meeting_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
